services:
  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - ${MONGO_INITDB_PORT}:27017
  
  api:
    build: .
    container_name: api
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_API_HOST: ${MONGO_API_HOST}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mongo:
        condition: service_started
    links:
      - mongo

volumes:
  mongo:
